---
- name: Deploy Calculator Application
  hosts: localhost
  remote_user: user
  become: false
  tasks:
    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "omkarsatav/calculator:latest"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Remove existing container if it exists
      command: docker rm -f scientific_calculator
      ignore_errors: yes

    - name: Running container
      command: docker run -it -d --name scientific_calculator omkarsatav/calculator:latest
