---
- name: Deploy Calculator Application
  hosts: localhost
  remote_user: user
  become: false
  tasks:
    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "omkarsatav/scientific_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name scientific_calculator -p 9090:8080 omkarsatav/scientific_calculator
